### ISSUE TITLE
Ask for permission before overwriting an existing zathurarc file

### ISSUE THREAD

**Issue by kartikynwa** [gennaro-tedesco/zathuraconf#3]
Users might already have a zathurarc in place and losing it could be unfortunate. It would be nice if the program asked for permission before overwriting an existing file or could even refuse to do this.

Thanks.

**Comment by gennaro-tedesco** [comment]
Thank you for your suggestion! One way to implement this could be to provide a flag, say `-f/--force`, that defaults to `false` (thereby asking the user for confirmation). Something along the lines of 
```
zathuraconf config.json  <--- prompts for permission
```
```
zathuraconf -f config.json <--- force the overwrite, don't ask
```
I will work on it these days and prepare a pull request, then we can test if this is the behaviour we want.

**Comment by gennaro-tedesco** [comment]
I have drafted https://github.com/gennaro-tedesco/zathuraconf/pull/4. It should behave like shown below

![Screen-Recording-2021-04-11-at-2](https://user-images.githubusercontent.com/15387611/114319228-e7763d80-9b10-11eb-9477-c625f4072bc4.gif)

basically passing the `-f` forces overwrite, otherwise the user is prompted for explicit confirmation. Is this something along the lines of what you are imagining? If so, I will clean up the code, merge and release a new version.

**Comment by gennaro-tedesco** [comment]
I have release a [new version](https://github.com/gennaro-tedesco/zathuraconf/releases/tag/v1.1.0).

`Go get` it to fetch the latest version :)
